# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2880
cpus_per_task: 20
gpus_per_node: null
tasks_per_node: 1
mem_gb: 160
nodes: 1
name: AL-Embeddings
stderr_to_stdout: true
partition: main
qos: null
comment: null
constraint: null
exclude: gpu-v100-[1-4]
gres: gpu:1
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 5
setup:
- date
- source ~/.bashrc
- conda activate al-embeddings