batch_size: 100
name: HSN_scape

train:
  data:
    _target_: al_embeddings.data.Birdset

  load_dataset_kwargs:
    path: DBD-research-group/BirdSet
    name: HSN_scape
    cache_dir: ${paths.dataset_dir}/${dataset.name}
    trust_remote_code: True

  prepare_kwargs:
    null

test:
  split_size: 0.2