batch_size: 200
name: UHH_scape
train:
  data:
    _target_: al_embeddings.data.Birdset

  load_dataset_kwargs:
    path: DBD-research-group/BirdSet
    name: UHH_scape
    cache_dir: ${paths.dataset_dir}/${dataset.name}
    trust_remote_code: True

  prepare_kwargs:
    null

test:
  split_size: 0.3