name: LC_average

strategy:
  _target_: skactiveml.pool.UncertaintySampling
  method: least_confident
  random_state: ${random_seed}
  ml_agg:
    _target_: numpy.average
    _partial_: True

query_kwargs:
  batch_size: ${dataset.batch_size}
  fit_clf: False
