name: margin

strategy:
  _target_: skactiveml.pool.UncertaintySampling
  method: margin_sampling
  random_state: ${random_seed}

query_kwargs:
  batch_size: ${dataset.batch_size} # acq_size
  fit_clf: False