name: MMC

strategy:
  _target_: skactiveml.pool.MMC
  random_state: ${random_seed}

query_kwargs:
  batch_size: ${dataset.batch_size}
  fit_clf: False
  discriminator:
    _target_: skactiveml.classifier.SklearnClassifier
    estimator:
      _target_: sklearn.linear_model.LogisticRegression
      max_iter: 1000
      n_jobs: -1
      random_state: ${random_seed}